<?php if ($isClientLogged || $isAdminLogged): ?>

    <!--when clicked in edit button in authorInfo. Client arrives here to edit-->
    
    <?php if (array_key_exists("author_id", $_GET)) : ?>
    
            <h2>Edit Author </h2>
            <form class="input" action="index.php?action=editAuthor"  method="post">
                
                        <input type="hidden" name="author_id" value="<?= $author['author_id'] ?>"/>
                    
                    <label for="author_name"></label>
                        <input type="text" placeholder="author_name" name="author_name" value="<?= $author['author_name'] ?>">
                    <label for="author_surname"></label> 
                        <input type="text" placeholder="author_surname" name="author_surname" value="<?= $author['author_surname'] ?>">
                    <label for="author_email"></label> 
                        <input type="email" placeholder="author_email" name="author_email" value="<?= $author['author_email'] ?>">
                    <label for="author_phone"></label>
                        <input type="number" placeholder="author_phone" name="author_phone" value="<?= $author['author_phone'] ?>">
                    <label for="author_web"></label>
                        <input type="text" placeholder="author_web" name="author_web" value="<?= $author['author_web'] ?>">
                    <label for="author_ig"></label>
                        <input type="text" placeholder="author_ig" name="author_ig" value="<?= $author['author_ig'] ?>">
                        
                <input type="submit" value="add/edit">
                <input type="submit" value="reset">
            </form>
    <?php endif ; ?>
   
 <!--After submit, reload authorInfo.phtm with a require or include??? -->
 
<?php else : ?>    
    <p>Only available to logged clients</p>
<?php endif; ?>
