 <!--Create Client form-->
 <h2> CreateClient form</h2>
 <form class="input" action="index.php?action=createClient"  method="post">
 
    <label for="create_name"></label>
        <input type="text" placeholder="client_name" name="client_name">
        
    <label for="client_surname"></label> 
        <input type="text" placeholder="client_surname" name="client_surname">
        
    <label for="client_email"></label> 
        <input type="email" placeholder="client_email" name="client_email">
        
    <label for="client_phone"></label>
        <input type="number" placeholder="client_phone" name="client_phone">
        
    <label for="password"></label>
        <input type="password" placeholder="client_password" name="client_password">           

        <input type="submit" value="createClient">
</form>

 