<?php $ClientController = new ClientController(); ?>

        <form class="input" action="index.php?action=loginClient"  method="post">
            <label for="email"></label>
            <input type="text" placeholder="client_email" name="client_email">
            
            <label for="password"></label>
            <input type="password" placeholder="client_password" name="client_password">
            
            <input type="submit" value="login">
        </form>
        

  
    