<?php $AdminController = new AdminController(); ?>

<!--Login Admin input Form-->
<h2> LoginAdmin form</h2>

<form class="input" action="index.php?action=loginAdmin" method="post">
   
   	<label for="pseudo"></label>
    <input type="pseudo" placeholder="pseudo" name="admin_pseudo">

    <label for="email"></label>
    <input type="text" placeholder="email" name="admin_email">
    
    <label for="password"></label>
    <input type="password" placeholder="password" name="admin_password">

    <input type="submit" value="loginAdmin">
 </form>
