
<!--Create Admin input Form-->

<h2> CreateAdmin form</h2>

<form class="input" action="index.php?action=createAdmin" method="post">
    <label for="pseudo"></label>
    <input type="pseudo" placeholder="admin_pseudo" name="admin_pseudo">

    <label for="email"></label>
    <input type="text" placeholder="admin_email" name="admin_email">

    <label for="password"></label>
    <input type="password" placeholder="admin_password" name="admin_password">

    <input type="submit" value="createAdmin">
</form>